### ISSUE TITLE
Python for Loops Lab

### ISSUE THREAD

**Issue by KGharib** [learn-co-curriculum/for-loops-readme#14]
im not sure how to do the for loop when it comes to names_and_ranks
this is what i have until now

names_and_ranks = []
for index in city_indices:
    append_phrase = index+1,'.', city_names[index]
    names_and_ranks.append(append_phrase)
print(names_and_ranks)

**Comment by mas16** [comment]
Hi KGharib, thanks for posting! You can seek help using the ask a question feature in Learn. These posts are reserved for bugs or other technical issues with the lesson/lab. Thanks and good luck!
