### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by jackielebwohl** [learn-co-curriculum/for-loops-readme#3]
I think I found a typo in the code where we use list(range(0, len(countries))) to specify a range. I kept receiving an error message when running it as written:

for **i** in list(range(0, len(countries))):
    print(cities[index]+",", countries[index])

When I compared this code to the previous code we had been given it appears that it perhaps should have read:
for **index** in list(range(0, len(countries))):
    print(cities[index]+",", countries[index])

When I emended the code it seemed to run correctly.

**Comment by LoreDirick** [comment]
@jackielebwohl: correct - changed to `index` everywhere. Thanks!
