### ISSUE TITLE
Code in range example with typo

### ISSUE THREAD

**Issue by hsztan** [learn-co-curriculum/for-loops-readme#7]
Code reads:
`for i in list(range(0, len(countries))):
     print(cities[index]+",", countries[index])`

Should be:
`for i in list(range(0, len(countries))):
     print(cities[i]+",", countries[i])`

**Comment by kompaktor** [comment]
I found the same typo today. Solved similarly, by changing "i" to "index".

**Comment by LoreDirick** [comment]
@hsztan: correct - moved to `index` everywhere instead of `i`. Thanks!
