### ISSUE TITLE
Bug in piece of code for Lesson _For Loops Readme_

### ISSUE THREAD

**Issue by fpleoni** [learn-co-curriculum/for-loops-readme#9]
In lesson _For Loops Readme_

```
for i in list(range(0, len(countries))):
    print(cities[index]+",", countries[index]) 
```
Has a bug. Inside the **[]** it should be **_i_** instead of **index**

Same with the next piece of code:

```
countries.append('Mexico')
cities.append('Mexico City')
for i in list(range(0, len(countries))):
    print(cities[index]+",", countries[index])
```

Unless this is intentional so that the student debugs the code, and changes **index** for **i** - or in more abstract terms, for the student to be mindful of consistency of arguments in for loops.

**Comment by LoreDirick** [comment]
@fpleoni : correct - moved to `index` everywhere instead of `i`. Thanks!
